### ISSUE TITLE
Media-specific information in MAF API

### ISSUE THREAD

**Issue by ibouazizi** [MPEGGroup/Scene-Description#8]
Another issue with the MAF API is the lack of indication of additional information to correctly format the buffer data by the media pipeline. In particular the following information is missing:
•	width and height of a video texture frame as expected in the buffer by the Presentation Engine.
•	format and color space of a video texture frame
•	sample rate of the audio
We suggest that a new structure be defined with the name OutputMediaInfo. This structure would be added to the BufferInfo structure as an optional element. Depending on the attributeType, different sets of data will be provided in the OutputMediaInfo structure.

**Comment by gurdep** [comment]
Hi @ibouazizi ,
`width` and `height` of the data in the buffer is also provided in the buffer frame header. It is advised to discuss the relevance of the `width` and `height` entities in the buffer frame header to address the issue. If the new structure e.g. `OutputMediaInfo` is an alternative to the information available in the buffer frame header, it should be clarified. The expected behavior should be clarified in case both or either of the options are available.

**Comment by haudiobe** [comment]
Addressed in Amd.2
